// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Prismic Test Flag documents
 */
interface PrismicTestFlagDocumentData {
  /**
   * test field in *Prismic Test Flag*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: prismic_test_flag.test
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  test: prismic.BooleanField;

  /**
   * test2 field in *Prismic Test Flag*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: prismic_test_flag.test2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  test2: prismic.BooleanField;

  /**
   * test3 field in *Prismic Test Flag*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: prismic_test_flag.test3
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  test3: prismic.BooleanField;

  /**
   * testFlag field in *Prismic Test Flag*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: prismic_test_flag.testflag
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  testflag: prismic.BooleanField;
}

/**
 * Prismic Test Flag document from Prismic
 *
 * - **API ID**: `prismic_test_flag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PrismicTestFlagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PrismicTestFlagDocumentData>,
    "prismic_test_flag",
    Lang
  >;

type TestDocumentDataSlicesSlice = TestSlice;

/**
 * Content for Test documents
 */
interface TestDocumentData {
  /**
   * Slice Zone field in *Test*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: test.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: test.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Test*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Test*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: test.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Test document from Prismic
 *
 * - **API ID**: `test`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<TestDocumentData>, "test", Lang>;

type TestFlagDocumentDataSlicesSlice = TestSlice;

/**
 * Content for Test Flag documents
 */
interface TestFlagDocumentData {
  /**
   * Slice Zone field in *Test Flag*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: test_flag.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TestFlagDocumentDataSlicesSlice>
  /**
   * Meta Description field in *Test Flag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: test_flag.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Test Flag*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: test_flag.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Test Flag*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: test_flag.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Test Flag document from Prismic
 *
 * - **API ID**: `test_flag`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestFlagDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TestFlagDocumentData>,
    "test_flag",
    Lang
  >;

export type AllDocumentTypes =
  | PrismicTestFlagDocument
  | TestDocument
  | TestFlagDocument;

/**
 * Default variation for Test Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *Test*
 */
type TestSliceVariation = TestSliceDefault;

/**
 * Test Shared Slice
 *
 * - **API ID**: `test`
 * - **Description**: Test
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestSlice = prismic.SharedSlice<"test", TestSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PrismicTestFlagDocument,
      PrismicTestFlagDocumentData,
      TestDocument,
      TestDocumentData,
      TestDocumentDataSlicesSlice,
      TestFlagDocument,
      TestFlagDocumentData,
      TestFlagDocumentDataSlicesSlice,
      AllDocumentTypes,
      TestSlice,
      TestSliceVariation,
      TestSliceDefault,
    };
  }
}
